apiVersion: v1
kind: Namespace
metadata:
  name: cowin

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: head-detection
  namespace: cowin
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: head-detection
      version: 'v1'
  template:
    metadata:
      labels:
        app: head-detection
        version: 'v1'
    spec:
      containers:
        - name: head-detection
          image: vamsikkv/head-detection:latest
          

          ports:
            - name: http
              containerPort: 5000
          
          resources:
            requests:
              memory: '3Gi'
              cpu: '1'
            limits:
              memory: '8Gi'
              cpu: '4.5'

       

